# Generated by Django 5.0.6 on 2024-05-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('documents', models.URLField(blank=True, null=True)),
                ('point_of_contact', models.CharField(max_length=255)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('service_type', models.CharField(max_length=255)),
                ('last_maintained', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
